use crate::ast::*;

pub fn emit_rust(program: &Program) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "// Generated by verbosec {}.{}.{}\n",
        program.version.major, program.version.minor, program.version.patch
    ));
    out.push_str("// This file was compiled from Verbose IR. Do not edit by hand.\n");
    for item in &program.items {
        match item {
            Item::Concept(c) => {
                let fields: Vec<String> = c
                    .fields
                    .iter()
                    .map(|f| format!("{}: {}", f.name, type_label(&f.ty)))
                    .collect();
                out.push_str(&format!("// Concept: {} ({})\n", c.name, fields.join(", ")));
            }
            Item::Rule(r) => {
                out.push_str(&format!("// Rule: {} — \"{}\"\n", r.name, r.intention));
            }
        }
    }
    out.push('\n');

    out.push_str("#![allow(unused_variables)]\n\n");
    out.push_str("use std::collections::HashMap;\n");
    out.push_str("use std::env;\n");
    out.push_str("use std::fs;\n\n");

    let concepts: Vec<&Concept> = program
        .items
        .iter()
        .filter_map(|i| match i {
            Item::Concept(c) => Some(c),
            _ => None,
        })
        .collect();

    for item in &program.items {
        if let Item::Rule(rule) = item {
            let concept = find_concept(&concepts, &rule.input_ty);
            emit_rule_fn(&mut out, rule, concept);
        }
    }

    emit_main(&mut out, program, &concepts);
    out.push_str(&json_runtime());

    out
}

fn find_concept<'a>(concepts: &[&'a Concept], ty: &Type) -> Option<&'a Concept> {
    match ty {
        Type::Named(n) => concepts.iter().find(|c| c.name == *n).copied(),
        _ => None,
    }
}

fn emit_rule_fn(out: &mut String, rule: &Rule, concept: Option<&Concept>) {
    out.push_str(&format!("/// {}\n", rule.intention));
    out.push_str(&format!("fn {}(", rule.name));

    if let Some(c) = concept {
        for (i, field) in c.fields.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{}: {}", field.name, rust_type(&field.ty)));
        }
    }

    out.push_str(&format!(") -> {} {{\n", rust_type(&rule.output_ty)));
    out.push_str(&format!(
        "    {}\n",
        emit_expr(&rule.logic.value, &rule.input_name)
    ));
    out.push_str("}\n\n");
}

fn emit_main(out: &mut String, program: &Program, concepts: &[&Concept]) {
    out.push_str("fn main() {\n");
    out.push_str(
        "    let path = env::args().nth(1).expect(\"usage: program <data.json>\");\n",
    );
    out.push_str(
        "    let content = fs::read_to_string(&path).expect(\"cannot read input file\");\n",
    );
    out.push_str("    let records = parse_json_array(&content);\n");

    for item in &program.items {
        if let Item::Rule(rule) = item {
            let concept = find_concept(concepts, &rule.input_ty);

            out.push_str("    for (idx, rec) in records.iter().enumerate() {\n");

            if let Some(c) = concept {
                for field in &c.fields {
                    out.push_str(&format!(
                        "        let {} = rec[\"{}\"];\n",
                        field.name, field.name
                    ));
                }
                let args: Vec<&str> = c.fields.iter().map(|f| f.name.as_str()).collect();
                out.push_str(&format!(
                    "        let result = {}({});\n",
                    rule.name,
                    args.join(", ")
                ));
            }

            out.push_str(&format!(
                "        println!(\"[{{}}] {} = {{}}\", idx, result);\n",
                rule.output_name
            ));
            out.push_str("    }\n");
        }
    }

    out.push_str("}\n\n");
}

fn emit_expr(expr: &Expr, input_name: &str) -> String {
    match expr {
        Expr::Number(n) => format!("{}", n),
        Expr::Ident(name) => name.clone(),
        Expr::Field(base, field) => {
            if matches!(base.as_ref(), Expr::Ident(n) if n == input_name) {
                field.clone()
            } else {
                format!("{}.{}", emit_expr(base, input_name), field)
            }
        }
        Expr::Binary(op, l, r) => {
            let op_str = match op {
                BinOp::Gt => ">",
                BinOp::Lt => "<",
                BinOp::GtEq => ">=",
                BinOp::LtEq => "<=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!(
                "{} {} {}",
                emit_expr(l, input_name),
                op_str,
                emit_expr(r, input_name)
            )
        }
    }
}

fn rust_type(ty: &Type) -> &str {
    match ty {
        Type::Number => "i64",
        Type::Bool => "bool",
        Type::Named(_) => "i64",
    }
}

fn type_label(ty: &Type) -> &str {
    match ty {
        Type::Number => "number",
        Type::Bool => "bool",
        Type::Named(n) => n.as_str(),
    }
}

fn json_runtime() -> String {
    r#"fn parse_json_array(s: &str) -> Vec<HashMap<String, i64>> {
    let s = s.trim();
    let inner = &s[1..s.len() - 1];
    let mut records = Vec::new();
    let mut depth = 0i32;
    let mut start = 0;
    for (i, c) in inner.char_indices() {
        match c {
            '{' => depth += 1,
            '}' => depth -= 1,
            ',' if depth == 0 => {
                let chunk = inner[start..i].trim();
                if !chunk.is_empty() {
                    records.push(parse_json_object(chunk));
                }
                start = i + 1;
            }
            _ => {}
        }
    }
    let last = inner[start..].trim();
    if !last.is_empty() {
        records.push(parse_json_object(last));
    }
    records
}

fn parse_json_object(s: &str) -> HashMap<String, i64> {
    let s = s.trim();
    let inner = &s[1..s.len() - 1];
    let mut map = HashMap::new();
    for pair in inner.split(',') {
        let pair = pair.trim();
        if pair.is_empty() {
            continue;
        }
        let colon = pair.find(':').unwrap();
        let key = pair[..colon].trim().trim_matches('"');
        let val: i64 = pair[colon + 1..].trim().parse().unwrap();
        map.insert(key.to_string(), val);
    }
    map
}
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_number() {
        assert_eq!(emit_expr(&Expr::Number(42), "i"), "42");
    }

    #[test]
    fn emit_field_access() {
        let expr = Expr::Field(Box::new(Expr::Ident("i".into())), "amount".into());
        assert_eq!(emit_expr(&expr, "i"), "amount");
    }

    #[test]
    fn emit_comparison() {
        let expr = Expr::Binary(
            BinOp::Gt,
            Box::new(Expr::Field(
                Box::new(Expr::Ident("i".into())),
                "amount".into(),
            )),
            Box::new(Expr::Number(10000)),
        );
        assert_eq!(emit_expr(&expr, "i"), "amount > 10000");
    }

    #[test]
    fn full_program_generates_valid_structure() {
        let program = Program {
            version: Version {
                major: 0,
                minor: 1,
                patch: 0,
            },
            items: vec![
                Item::Concept(Concept {
                    name: "Foo".into(),
                    intention: "a foo".into(),
                    source: SourceRef {
                        file: "f.intent".into(),
                        line: 1,
                    },
                    fields: vec![Field {
                        name: "x".into(),
                        ty: Type::Number,
                    }],
                }),
                Item::Rule(Rule {
                    name: "check_foo".into(),
                    intention: "check it".into(),
                    source: SourceRef {
                        file: "f.intent".into(),
                        line: 2,
                    },
                    input_name: "f".into(),
                    input_ty: Type::Named("Foo".into()),
                    output_name: "ok".into(),
                    output_ty: Type::Bool,
                    logic: LogicStmt {
                        target: "ok".into(),
                        value: Expr::Binary(
                            BinOp::Gt,
                            Box::new(Expr::Field(
                                Box::new(Expr::Ident("f".into())),
                                "x".into(),
                            )),
                            Box::new(Expr::Number(0)),
                        ),
                    },
                    proofs: Proofs {
                        purity: Purity {
                            reads: vec![Path {
                                segments: vec!["f".into(), "x".into()],
                            }],
                            writes: vec![],
                            calls: vec![],
                            verdict: PurityVerdict::Pure,
                        },
                        termination: Termination {
                            form: TerminationForm::ConstantBound,
                            bound: Some(1),
                        },
                        determinism: Determinism {
                            form: DeterminismForm::Total,
                        },
                    },
                }),
            ],
        };
        let rust = emit_rust(&program);
        assert!(rust.contains("fn check_foo(x: i64) -> bool"));
        assert!(rust.contains("x > 0"));
        assert!(rust.contains("fn main()"));
        assert!(rust.contains("parse_json_array"));
    }
}
