use crate::ast::*;

pub fn emit_rust(program: &Program) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "// Generated by verbosec {}.{}.{}\n",
        program.version.major, program.version.minor, program.version.patch
    ));
    out.push_str("// This file was compiled from Verbose IR. Do not edit by hand.\n");
    for item in &program.items {
        match item {
            Item::Concept(c) => {
                let fields: Vec<String> = c
                    .fields
                    .iter()
                    .map(|f| format!("{}: {}", f.name, type_label(&f.ty)))
                    .collect();
                out.push_str(&format!("// Concept: {} ({})\n", c.name, fields.join(", ")));
            }
            Item::Rule(r) => {
                out.push_str(&format!("// Rule: {} — \"{}\"\n", r.name, r.intention));
            }
            Item::Reaction(rx) => {
                out.push_str(&format!("// Reaction: {} — \"{}\"\n", rx.name, rx.intention));
            }
            Item::Service(s) => {
                // Phase 7 services are declarative network listeners. The
                // Rust transpiler does not emit servers today — it targets
                // pure-rule transpilation. Skip with a comment so the output
                // stays coherent.
                out.push_str(&format!("// Service: {} — \"{}\" (not transpiled; Phase 7 native-only)\n", s.name, s.intention));
            }
            Item::Resource(r) => {
                // Phase 9 slice 1: file resources are native-only today.
                // Comment out for the Rust transpiler so the output stays
                // coherent; rules that reference read(...) will fail a later
                // pass when we add transpiler support for file I/O.
                out.push_str(&format!(
                    "// Resource: {} — \"{}\" → {} [max {}] (not transpiled; native-only)\n",
                    r.name, r.intention, r.path, r.max_bytes
                ));
            }
            Item::Connection(c) => {
                // Phase 11 slice 1: TCP connections are native-only today.
                // Same handling as Resource — emit a header comment so the
                // output stays coherent; rules that reference fetch(...)
                // will fail a later pass when we add transpiler support
                // for TCP I/O.
                out.push_str(&format!(
                    "// Connection: {} — \"{}\" → {}:{} [max_response {}] (not transpiled; native-only)\n",
                    c.name, c.intention, c.host, c.port, c.max_response
                ));
            }
        }
    }
    out.push('\n');

    out.push_str("#![allow(unused_variables)]\n\n");
    out.push_str("use std::collections::HashMap;\n");
    out.push_str("use std::env;\n");
    out.push_str("use std::fs;\n\n");

    let concepts: Vec<&Concept> = program
        .items
        .iter()
        .filter_map(|i| match i {
            Item::Concept(c) => Some(c),
            _ => None,
        })
        .collect();

    for item in &program.items {
        if let Item::Rule(rule) = item {
            let concept = find_concept(&concepts, &rule.input_ty);
            emit_rule_fn(&mut out, rule, concept);
        }
    }

    emit_main(&mut out, program, &concepts);
    out.push_str(&json_runtime());

    out
}

fn find_concept<'a>(concepts: &[&'a Concept], ty: &Type) -> Option<&'a Concept> {
    match ty {
        Type::Named(n) => concepts.iter().find(|c| c.name == *n).copied(),
        _ => None,
    }
}

fn emit_rule_fn(out: &mut String, rule: &Rule, concept: Option<&Concept>) {
    out.push_str(&format!("/// {}\n", rule.intention));
    out.push_str(&format!("fn {}(", rule.name));

    if let Some(c) = concept {
        for (i, field) in c.fields.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{}: {}", field.name, rust_type(&field.ty)));
        }
    }

    out.push_str(&format!(") -> {} {{\n", rust_type(&rule.output_ty)));
    for (name, expr) in &rule.logic.bindings {
        out.push_str(&format!(
            "    let {} = {};\n",
            name,
            emit_expr(expr, &rule.input_name, concept)
        ));
    }
    out.push_str(&format!(
        "    {}\n",
        emit_expr(&rule.logic.value, &rule.input_name, concept)
    ));
    out.push_str("}\n\n");
}

fn emit_main(out: &mut String, program: &Program, concepts: &[&Concept]) {
    out.push_str("fn main() {\n");
    out.push_str(
        "    let path = env::args().nth(1).expect(\"usage: program <data.json>\");\n",
    );
    out.push_str(
        "    let content = fs::read_to_string(&path).expect(\"cannot read input file\");\n",
    );
    out.push_str("    let records = parse_json_array(&content);\n");

    for item in &program.items {
        if let Item::Rule(rule) = item {
            let concept = find_concept(concepts, &rule.input_ty);

            out.push_str("    for (idx, rec) in records.iter().enumerate() {\n");

            if let Some(c) = concept {
                for field in &c.fields {
                    out.push_str(&format!(
                        "        let {} = rec[\"{}\"];\n",
                        field.name, field.name
                    ));
                }
                let args: Vec<&str> = c.fields.iter().map(|f| f.name.as_str()).collect();
                out.push_str(&format!(
                    "        let result = {}({});\n",
                    rule.name,
                    args.join(", ")
                ));
            }

            out.push_str(&format!(
                "        println!(\"[{{}}] {} = {{}}\", idx, result);\n",
                rule.output_name
            ));
            out.push_str("    }\n");
        }
    }

    out.push_str("}\n\n");
}

fn emit_expr(expr: &Expr, input_name: &str, concept: Option<&Concept>) -> String {
    match expr {
        Expr::Number(n) => format!("{}", n),
        Expr::Text(s) => format!("{:?}", s),
        Expr::Ident(name) => name.clone(),
        Expr::Field(base, field) => {
            if matches!(base.as_ref(), Expr::Ident(n) if n == input_name) {
                field.clone()
            } else {
                format!("{}.{}", emit_expr(base, input_name, concept), field)
            }
        }
        Expr::Binary(op, l, r) => {
            let op_str = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::Eq => "==",
                BinOp::NotEq => "!=",
                BinOp::Gt => ">",
                BinOp::Lt => "<",
                BinOp::GtEq => ">=",
                BinOp::LtEq => "<=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!(
                "{} {} {}",
                emit_expr(l, input_name, concept),
                op_str,
                emit_expr(r, input_name, concept)
            )
        }
        Expr::If(cond, then_e, else_e) => format!(
            "if {} {{ {} }} else {{ {} }}",
            emit_expr(cond, input_name, concept),
            emit_expr(then_e, input_name, concept),
            emit_expr(else_e, input_name, concept),
        ),
        Expr::Not(inner) => format!("!{}", emit_expr(inner, input_name, concept)),
        Expr::Neg(inner) => format!("-{}", emit_expr(inner, input_name, concept)),
        Expr::Fold(_, _, _, _, _)
        | Expr::Quantifier(_, _, _, _)
        | Expr::Map(_, _, _)
        | Expr::Filter(_, _, _)
        | Expr::Ok(_)
        | Expr::Err(_)
        | Expr::MatchResult(_, _, _, _, _)
        | Expr::Record(_, _)
        | Expr::Concat(_)
        | Expr::Read(_)
        | Expr::Fetch(_, _)
        | Expr::JsonEscape(_)
        | Expr::ParseInt(_) => {
            "(/* collection/result/record/concat/read/fetch/json_escape/parse_int op: use --run interpreter or --native */false)".to_string()
        }
        Expr::Call(name, _args) => {
            if let Some(c) = concept {
                let fields: Vec<&str> = c.fields.iter().map(|f| f.name.as_str()).collect();
                format!("{}({})", name, fields.join(", "))
            } else {
                format!("{}()", name)
            }
        }
    }
}

fn rust_type(ty: &Type) -> &str {
    match ty {
        Type::Number => "i64",
        Type::Bool => "bool",
        Type::Text => "&str",
        // Bytes is introduced by Phase 7 for raw-TCP handlers; the Rust
        // transpiler does not lower it today — native is the target.
        Type::Bytes => "&[u8] /* Bytes — native backend target, not transpiled */",
        Type::Collection(_) => "Vec<i64>",
        Type::Named(_) => "i64",
        // Result(T, E) isn't lowered by the transpiler yet — the interpreter
        // is the current home. Surfaced as a placeholder so the transpiled
        // Rust file compiles but obviously won't execute Result semantics.
        Type::Result(_, _) => "i64 /* Result — use --run interpreter */",
    }
}

fn type_label(ty: &Type) -> &str {
    match ty {
        Type::Number => "number",
        Type::Bool => "bool",
        Type::Text => "text",
        Type::Bytes => "bytes",
        Type::Collection(inner) => return format!("collection({})", inner).leak(),
        Type::Named(n) => n.as_str(),
        Type::Result(t, e) => {
            return format!("Result({}, {})", type_label(t), type_label(e)).leak();
        }
    }
}

fn json_runtime() -> String {
    r#"fn parse_json_array(s: &str) -> Vec<HashMap<String, i64>> {
    let s = s.trim();
    let inner = &s[1..s.len() - 1];
    let mut records = Vec::new();
    let mut depth = 0i32;
    let mut start = 0;
    for (i, c) in inner.char_indices() {
        match c {
            '{' => depth += 1,
            '}' => depth -= 1,
            ',' if depth == 0 => {
                let chunk = inner[start..i].trim();
                if !chunk.is_empty() {
                    records.push(parse_json_object(chunk));
                }
                start = i + 1;
            }
            _ => {}
        }
    }
    let last = inner[start..].trim();
    if !last.is_empty() {
        records.push(parse_json_object(last));
    }
    records
}

fn parse_json_object(s: &str) -> HashMap<String, i64> {
    let s = s.trim();
    let inner = &s[1..s.len() - 1];
    let mut map = HashMap::new();
    for pair in inner.split(',') {
        let pair = pair.trim();
        if pair.is_empty() {
            continue;
        }
        let colon = pair.find(':').unwrap();
        let key = pair[..colon].trim().trim_matches('"');
        let val: i64 = pair[colon + 1..].trim().parse().unwrap();
        map.insert(key.to_string(), val);
    }
    map
}
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_number() {
        assert_eq!(emit_expr(&Expr::Number(42), "i", None), "42");
    }

    #[test]
    fn emit_field_access() {
        let expr = Expr::Field(Box::new(Expr::Ident("i".into())), "amount".into());
        assert_eq!(emit_expr(&expr, "i", None), "amount");
    }

    #[test]
    fn emit_comparison() {
        let expr = Expr::Binary(
            BinOp::Gt,
            Box::new(Expr::Field(
                Box::new(Expr::Ident("i".into())),
                "amount".into(),
            )),
            Box::new(Expr::Number(10000)),
        );
        assert_eq!(emit_expr(&expr, "i", None), "amount > 10000");
    }

    #[test]
    fn full_program_generates_valid_structure() {
        let program = Program {
            version: Version {
                major: 0,
                minor: 1,
                patch: 0,
            },
            items: vec![
                Item::Concept(Concept {
                    name: "Foo".into(),
                    intention: "a foo".into(),
                    source: SourceRef {
                        file: "f.intent".into(),
                        line: 1,
                    },
                    fields: vec![Field {
                        name: "x".into(),
                        ty: Type::Number,
                    range: None,
                    }],
                }),
                Item::Rule(Rule {
                    name: "check_foo".into(),
                    intention: "check it".into(),
                    source: SourceRef {
                        file: "f.intent".into(),
                        line: 2,
                    },
                    input_name: "f".into(),
                    input_ty: Type::Named("Foo".into()),
                    output_name: "ok".into(),
                    output_ty: Type::Bool,
                    logic: LogicStmt {
                        bindings: vec![],
                        target: "ok".into(),
                        value: Expr::Binary(
                            BinOp::Gt,
                            Box::new(Expr::Field(
                                Box::new(Expr::Ident("f".into())),
                                "x".into(),
                            )),
                            Box::new(Expr::Number(0)),
                        ),
                    },
                    proofs: Proofs {
                        purity: Purity {
                            reads: vec![Path {
                                segments: vec!["f".into(), "x".into()],
                            }],
                            calls: vec![],
                        },
                        termination: Termination {
                            bound: Some(1),
                        },
                    },
                    hints: None,
                    layer: None,
                    context_name: None,
                    context_ty: None,
                }),
            ],
                uses: vec![],
        };
        let rust = emit_rust(&program);
        assert!(rust.contains("fn check_foo(x: i64) -> bool"));
        assert!(rust.contains("x > 0"));
        assert!(rust.contains("fn main()"));
        assert!(rust.contains("parse_json_array"));
    }

    #[test]
    fn emit_if_else() {
        let expr = Expr::If(
            Box::new(Expr::Binary(
                BinOp::Gt,
                Box::new(Expr::Field(Box::new(Expr::Ident("i".into())), "x".into())),
                Box::new(Expr::Number(10)),
            )),
            Box::new(Expr::Number(1)),
            Box::new(Expr::Number(0)),
        );
        let result = emit_expr(&expr, "i", None);
        assert!(result.contains("if"), "got: {}", result);
        assert!(result.contains("else"), "got: {}", result);
    }

    #[test]
    fn emit_not() {
        let expr = Expr::Not(Box::new(Expr::Ident("x".into())));
        let result = emit_expr(&expr, "i", None);
        assert_eq!(result, "!x");
    }

    #[test]
    fn emit_call() {
        let fields = vec![
            Field { name: "a".into(), ty: Type::Number, range: None },
            Field { name: "b".into(), ty: Type::Number, range: None },
        ];
        let concept = Concept {
            name: "T".into(),
            intention: "t".into(),
            source: SourceRef { file: "t".into(), line: 1 },
            fields,
        };
        let expr = Expr::Call("other_rule".into(), vec![Expr::Ident("i".into())]);
        let result = emit_expr(&expr, "i", Some(&concept));
        assert_eq!(result, "other_rule(a, b)");
    }
}
